swagger: '2.0'
info:
  version: v1.0
  title: GrowthZone Document Generation Fields API
  description: The API Description
host: app.memberzone.org
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:

  /api/documentgenerationfields:
    get:
      tags:
        - DocumentGenerationFields
      description:
        "Returns all of the document generation metadata."
      responses:
        200:
          description:
            "The list of document metadata that are available."
          schema:
            type: array
            items:
              properties:
                Name:
                  type: string
                  description: "Returns the name of the document type."
                Categories:
                  type: string
                  description: "Returns the list of categories available for the document type."
