swagger: '2.0'
info:
  version: v1
  title: MMP API
  description: The API description for the MicroNet MMP system.
host: app.memberzone.org
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  $ref: account.yaml
